#!/bin/bash
set -e -a

#########################################################################

: ${LS_HOME:=/lustre/orion/proj-shared/csc262/ylan/src/lsbench-run}
: ${LS_CC:="cc"}
: ${LS_CXX:="CC"}

: ${ENABLE_CUDA:=0}   # NOT tested
: ${ENABLE_HIP:=1}    # ok
: ${ENABLE_DPCPP:=0}  # NOT tested

: ${ENABLE_CUSPARSE:=0}
: ${ENABLE_HYPRE:=1}
: ${ENABLE_AMGX:=0}
: ${ENABLE_CHOLMOD:=0}
: ${ENABLE_PARALMOND:=0}
: ${ENABLE_ROCALUTION:=1}
: ${ENABLE_GINKGO:=1}

#########################################################################

: ${NRSCONFIG_NOBUILD:=0}

cmake -S . -B build \
      -Wno-dev \
      -Wfatal-errors \
      -DCMAKE_INSTALL_PREFIX="${LS_HOME}" \
      -DCMAKE_C_COMPILER="${LS_CC}" \
      -DCMAKE_CXX_COMPILER="${LS_CXX}" \
      -DENABLE_CUDA="${ENABLE_CUDA}" \
      -DENABLE_HIP="${ENABLE_HIP}" \
      -DENABLE_DPCPP="${ENABLE_DPCPP}" \
      -DENABLE_CUSPARSE="${ENABLE_CUSPARSE}" \
      -DENABLE_AMGX=${ENABLE_AMGX} \
      -DENABLE_HYPRE="${ENABLE_HYPRE}" \
      -DENABLE_CHOLMOD="${ENABLE_CHOLMOD}" \
      -DENABLE_PARALMOND="${ENABLE_PARALMOND}" \
      -DENABLE_ROCALUTION="${ENABLE_ROCALUTION}" \
      -DENABLE_GINKGO="${ENABLE_GINKGO}" \
      $@

if [ $? -eq 0 ] && [ ${NRSCONFIG_NOBUILD} -eq 0 ]; then
  cmd="cmake --build ./build --target install -j10"
  echo ""
  read -p "Hit enter to build code: $cmd"
  $cmd

  if [ $? -eq 0 ]; then
    echo ""
    echo -e "\033[35mHooray! You're all set. The installation is complete.\033[m"
    echo ""
  fi
fi
